[build]
  publish = "frontend"
  functions = "backend"

[[redirects]]
  from = "/api/chat"
  to = "/.netlify/functions/chat"
  status = 200

[[redirects]]
  from = "/api/sessions"
  to = "/.netlify/functions/sessions"
  status = 200

[[redirects]]
  from = "/api/favs"
  to = "/.netlify/functions/favs"
  status = 200

[[redirects]]
  from = "/api/auth"
  to = "/.netlify/functions/auth"
  status = 200
